### ISSUE TITLE
error using reconstruction_pipeline.py : no such filr or directory:matches_importer

### ISSUE THREAD

**Issue by Miranda0920** [ahojnnes/local-feature-evaluation#11]
When i use the command:

python3 scripts/reconstruction_pipeline.py --dataset_path data/Fountain/ --colmap_path ../colmap/build/src/exe

to eval the descriptor,error occurs:

Traceback (most recent call last):
  File "scripts/reconstruction_pipeline.py", line 277, in <module>
    main()
  File "scripts/reconstruction_pipeline.py", line 243, in main
    matching_stats = import_matches(args)
  File "scripts/reconstruction_pipeline.py", line 114, in import_matches
    "--match_type", "pairs"])
  File "/usr/lib/python3.5/subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '../colmap/build/src/exe/matches_importer'

But i can use the command "colmap matches_importer  --dataset_path data/Fountain --match_list_path data/Fountain/image-pairs.txt" correctly.

How to fix it? Looking forward to your apply!

**Comment by ahojnnes** [comment]
@kr0920 I am currently working on updating the benchmark with the newest COLMAP version. I will push several fixes over the next days. I will keep you updated.

**Comment by ahojnnes** [comment]
Sorry for the delay, but this should be fixed now. Note that the numbers are also updated with the latest COLMAP version.
