### ISSUE TITLE
how to generate 'database.db' by using 'matching_pipeline.m'

### ISSUE THREAD

**Issue by bfan** [ahojnnes/local-feature-evaluation#2]
Hello, I think it misses some files on this project. After running matching_pipeline.m (it misses pdist2.m to compute eculidean distance of descriptors, I used my own), I obtained some files in 'descriptors', 'keypoints', 'matches' as you described in the instruction. However, I can not continue the evaluation by using the python script 'reconstruction_pipeline.py', as it requires to input the database file, which I haven't find after running the matching_pipeline. I do found there is 'DATABASE_PATH' defined in the 'matching_pipeline.m', but I didn't find where it is used. Can you help me to fix the problem?

**Comment by ahojnnes** [comment]
First, it seems you didn't download all required files from the server, see steps 2 and 3 in the instructions (``Databases.tar.gz``). Next, the ``pdist2.m`` function should be provided by Matlab, see https://mathworks.com/help/stats/pdist2.html

Let me know if you have other questions.

**Comment by bfan** [comment]
Thank you for your quickly reply. I just tried and it works for small dataset. What should I do to prepare such a database if I want to use my own dataset with my custom feature extractor and matching (I already convert them to the required format as described in the instruction)?

**Comment by ahojnnes** [comment]
I will try to create instructions for that soon. I'll leave this issue open as a reminder for that.

**Comment by lovekittynine** [comment]
@bfan  after i have got descriptors , matches, keypoints,but when i run reconstruction_pipeline.py 
it outputs as follow:
Importing features for 0003.png
Importing features for 0007.png
Importing features for 0004.png
Importing features for 0005.png
Importing features for 0009.png
Importing features for 0000.png
Importing features for 0002.png
Importing features for 0006.png
Importing features for 0001.png
Importing features for 0010.png
Importing features for 0008.png
Importing matches for 0001.png --- 0003.png
Importing matches for 0004.png --- 0007.png
Importing matches for 0004.png --- 0005.png
Importing matches for 0005.png --- 0007.png
Importing matches for 0001.png --- 0008.png
Importing matches for 0004.png --- 0009.png
Importing matches for 0000.png --- 0010.png
Importing matches for 0001.png --- 0009.png
Importing matches for 0003.png --- 0005.png
Importing matches for 0005.png --- 0010.png
Importing matches for 0005.png --- 0009.png
Importing matches for 0003.png --- 0006.png
Importing matches for 0001.png --- 0002.png
Importing matches for 0007.png --- 0010.png
Importing matches for 0002.png --- 0008.png
Importing matches for 0002.png --- 0009.png
Importing matches for 0009.png --- 0010.png
Importing matches for 0000.png --- 0008.png
Importing matches for 0002.png --- 0006.png
Importing matches for 0006.png --- 0008.png
Importing matches for 0008.png --- 0009.png
Importing matches for 0000.png --- 0006.png
Importing matches for 0002.png --- 0007.png
Importing matches for 0006.png --- 0010.png
Importing matches for 0007.png --- 0008.png
Importing matches for 0003.png --- 0010.png
Importing matches for 0003.png --- 0004.png
Importing matches for 0002.png --- 0005.png
Importing matches for 0003.png --- 0009.png
Importing matches for 0004.png --- 0010.png
Importing matches for 0003.png --- 0008.png
Importing matches for 0000.png --- 0002.png
Importing matches for 0000.png --- 0005.png
Importing matches for 0006.png --- 0007.png
Importing matches for 0001.png --- 0010.png
Importing matches for 0000.png --- 0003.png
Importing matches for 0005.png --- 0008.png
Importing matches for 0000.png --- 0004.png
Importing matches for 0001.png --- 0004.png
Importing matches for 0003.png --- 0007.png
Importing matches for 0004.png --- 0008.png
Importing matches for 0004.png --- 0006.png
Importing matches for 0000.png --- 0009.png
Importing matches for 0002.png --- 0003.png
Importing matches for 0001.png --- 0005.png
Importing matches for 0002.png --- 0010.png
Importing matches for 0002.png --- 0004.png
Importing matches for 0006.png --- 0009.png
Importing matches for 0005.png --- 0006.png
Importing matches for 0001.png --- 0006.png
Importing matches for 0000.png --- 0001.png
Importing matches for 0007.png --- 0009.png
Importing matches for 0001.png --- 0007.png
Importing matches for 0000.png --- 0007.png
Importing matches for 0008.png --- 0010.png

==============================================================================
Custom feature matching
==============================================================================

Shader not supported by your hardware!
Framebuffer object not supported!
GL_ARB_texture_rectangle not supported!
ERROR: SiftGPU not fully supported

==============================================================================
Loading database
==============================================================================

Loading cameras... 11 in 0.000s
Loading matches... 0 in 0.000s
Loading images... 11 in 0.000s (connected 0)
Building correspondence graph... in 0.000s (ignored 0)

Elapsed time: 0.000 [minutes]

WARNING: No images with matches found in the database.

Warning: Could not reconstruct any model

==============================================================================
Raw statistics
==============================================================================
{'num_images': 11, 'num_inlier_matches': None, 'num_inlier_pairs': 0}
None

==============================================================================
Formatted statistics
==============================================================================
Traceback (most recent call last):
  File "reconstruction_pipeline.py", line 297, in <module>
    main()
  File "reconstruction_pipeline.py", line 293, in main
    matching_stats["num_inlier_matches"]])) + " |")
TypeError: 'NoneType' object is not subscriptable
WARNING: No images with matches found in the database.How should I do?Thank you very much!!!

**Comment by XiaojieLi11** [comment]
Hello! Have you solved the problem of creating database.db for the new dataset? @bfan

**Comment by XiaojieLi11** [comment]
Sorry to bother you, but I also ran into a problem, how do I create database.db file for a new data set? @ahojnnes
