### ISSUE TITLE
no such table: two_view_geometries

### ISSUE THREAD

**Issue by fantuslk** [ahojnnes/local-feature-evaluation#20]
Traceback (most recent call last):
  File "scripts/reconstruction_pipeline.py", line 304, in <module>
    main()
  File "scripts/reconstruction_pipeline.py", line 270, in main
    matching_stats = import_matches(args)
  File "scripts/reconstruction_pipeline.py", line 144, in import_matches
    cursor.execute("SELECT count(*) FROM two_view_geometries WHERE rows > 0;")
sqlite3.OperationalError: no such table: two_view_geometries.

 I've finished reconstruction_pipeline.py but got this error._

**Comment by fantuslk** [comment]
Sorry,I've finished matching_pipeline.py but when I run the reconstruction_pipeline.py but got this error.

**Comment by fantuslk** [comment]
@ahojnnes

**Comment by lijiaman** [comment]
met the same error. Could you share how to fix this? Thx!
